### PR TITLE
Add `uninstall` and `zap` stanzas

### PR DESCRIPTION
**Pull request by FnControlOption**
Reference: https://docs.brew.sh/Cask-Cookbook

## Stanza: `uninstall`

> `quit:` (string or array) - bundle IDs of running applications to quit

## Stanza: `zap`

> The `zap` stanza describes a more complete uninstallation of files associated with a cask.

### CODE REVIEW

**Comment by dail8859** [comment]
@woj-tek Thoughts on this? Looking at the documentation and the changes seem to make sense. Any comments/suggestions/issues you may be aware of?

**Comment by woj-tek** [comment]
Not sure if `uninstall` is needed as we don't use pgk format (see https://docs.brew.sh/Cask-Cookbook#stanza-uninstall)

`zap` is definitely helpful and list looks ok (not sure if NotepadNext uses anything else)

**Comment by FnControlOption** [comment]
> Not sure if `uninstall` is needed as we don't use pgk format (see https://docs.brew.sh/Cask-Cookbook#stanza-uninstall)

I tried `brew uninstall notepadnext` both with and without the `uninstall` stanza, and the app is closed only when that line is present

**Comment by woj-tek** [comment]
> I tried `brew uninstall notepadnext` both with and without the `uninstall` stanza, and the app is closed only when that line is present

Does it need to close the app though?

**Comment by FnControlOption** [comment]
No, but it would be strange to keep open an app that has been uninstalled. However, I don’t have any strong feelings on this, so feel free to delete the line.

**Comment by dail8859** [comment]
> No, but it would be strange to keep open an app that has been uninstalled.

I would assume this situation would be rare but I agree closing it would make sense. On most other systems (e.g. Windows) it won't let you uninstall it while it is running.

@FnControlOption Appreciate the PR! <3

**Pull request merged**
